# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserecord',
            name='recorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_course_record', to='crm.UserProfile', verbose_name='Recorder'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_course_record', to='crm.UserProfile', verbose_name='Teacher'),
        ),
    ]
