# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-05-15 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200509_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, to='crm.ClassList', verbose_name='Enrolled class'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='qq',
            field=models.CharField(default='1111111', help_text='QQ Number must be unique', max_length=64, verbose_name='QQ'),
            preserve_default=False,
        ),
    ]
